### ISSUE TITLE
Deprecation warnings

### ISSUE THREAD

**Issue by fpalluel** [ajainvivek/ember-cli-spinner#4]
Hello,
With recent versions of ember, deprecation warnings are shown : 
`"WARNING: Binding style attributes may introduce cross-site scripting vulnerabilities; please ensure that values being bound are properly escaped. For more information, including how to disable this warning, see http://emberjs.com/deprecations/v1.x/#toc_binding-style-attributes."`

**Comment by fpalluel** [comment]
A quick and dirty PR ;-)
#5

**Comment by ajainvivek** [comment]
Sure will review and merge. Thanks
