### ISSUE TITLE
Update ember-cli-htmlbars dependency

### ISSUE THREAD

**Issue by imkikus** [ajainvivek/ember-cli-spinner#6]
Could you please update the ember-cli-htmlbars dependency since there are issues with the dependency after updating ember from `v2.6.0` to `v2.7.0`

[Deprecation Ref](https://github.com/ember-cli/ember-cli-htmlbars/issues/77)

**Comment by ajainvivek** [comment]
Updated the version to latest ember-cli-htmlbars. Let me know if you still face issue.

**Comment by imkikus** [comment]
@ajainvivek Updation didn't help though :( I tried pushing a pull-request with the fixes, due to permission issues I couldn't. Could you please update the dependency version of `ember-cli-htmlbars` to `v1.0.11` ?

Also i see that the version of the `ember-cli-htmlbars` isn't updated in the master branch of yours
![image](https://cloud.githubusercontent.com/assets/10371390/17482392/3aba351e-5d9f-11e6-8706-15953f952584.png)
