### ISSUE TITLE
Please update to the latest version of ember-cli-htmlbars to avoid deprecation warnings 

### ISSUE THREAD

**Issue by joelpresence** [ajainvivek/ember-cli-spinner#8]
Hi, as per https://github.com/ember-cli/ember-cli-htmlbars/issues/77 , you are using an old version of ember-cli-htmlbars that is causing deprecation warnings.  Could you please update ember-cli-spinner to use the latest version of ember-cli-htmlbars (1.1.0) and push an updated version of ember-cli-spinner?

Thanks!

**Comment by ajainvivek** [comment]
Updated ember-cli-htmlbars to 1.1.0
